name: krapi_explorer
description: Explorer application for the krapi blockchain
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.2.0
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  riverpod: ^2.1.1
  flutter_riverpod: ^2.1.1
  uuid: ^3.0.7
  flutter_webrtc: ^0.9.17
  rxdart: ^0.27.7
  rxdart_ext: ^0.2.7
  async: ^2.9.0
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1
  quiver: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  freezed: ^2.3.1
  json_serializable: ^6.5.4
flutter:

  uses-material-design: true




