name: krapi_explorer
description: Explorer application for the krapi blockchain
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  flutter_krapi:
    git:
      url: "https://github.com/KrapiOrg/flutter_krapi"

  riverpod: ^2.1.1
  flutter_riverpod: ^2.1.1
  uuid: ^3.0.7
  async: ^2.9.0
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1
  quiver: ^3.1.0
  timelines: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
